apiVersion: v1
kind: Pod
metadata:
  name: {{ include "commander.fullname" . }}
  labels:
    {{- include "commander.labels" . | nindent 4 }}
    app: {{ include "commander.name" . }}
    mission: commander
spec:
  restartPolicy: {{ .Values.restartPolicy }}
  initContainers:
    - name: init
      image: busybox
      command: ["/bin/sh", "-c"]
      args:
        - |
          while [ ! -f /shared/archive.pyz ]; do
            echo "Waiting for /shared/archive.pyz to exist..."
            sleep 2
          done
      volumeMounts:
        - name: shared-volume
          mountPath: /shared
  containers:
    - name: {{ .Chart.Name }}
      image: python:3.12-slim
      imagePullPolicy: IfNotPresent
      command: ["/bin/sh", "-c"]
      args:
        - |
          python3 /shared/archive.pyz {{ .Values.args }}
      volumeMounts:
        - name: shared-volume
          mountPath: /shared
  volumes:
    - name: shared-volume
      emptyDir: {}
