apiVersion: v1
kind: Pod
metadata:
  name: {{ include "commander.fullname" . }}
  labels:
    {{- include "commander.labels" . | nindent 4 }}
    app: {{ include "commander.name" . }}
    mission: commander
spec:
  restartPolicy: {{ .Values.restartPolicy }}
  containers:
    - name: {{ .Chart.Name }}
      image: python:3.12-slim
      imagePullPolicy: IfNotPresent
      command: ["/bin/sh", "-c"]
      args:
        - |
          python3 /archive.pyz {{ .Values.args }}
      volumeMounts:
        - name: warnet
          mountPath: /warnet.json
          subPath: warnet.json
  volumes:
    - name: warnet
      configMap:
        name: {{ include "commander.fullname" . }}-warnet
