apiVersion: v1
kind: Service
metadata:
  name: {{ include "lnd.fullname" . }}
  labels:
    {{- include "lnd.labels" . | nindent 4 }}
    app: {{ include "lnd.fullname" . }} 
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.RPCPort }}
      targetPort: rpc
      protocol: TCP
      name: rpc
    - port: {{ .Values.P2PPort }}
      targetPort: p2p
      protocol: TCP
      name: p2p
    - port: {{ .Values.RestPort }}
      targetPort: rest
      protocol: TCP
      name: rest
# Add this to expose service - temporarily
    - port: 9332
      targetPort: prom-metrics
      protocol: TCP
      name: prometheus-metrics
  selector:
    {{- include "lnd.selectorLabels" . | nindent 4 }}
